### ISSUE TITLE
Android Blank Notification Icon

### ISSUE THREAD

**Issue by ryanpager** [phonegap/phonegap-plugin-push#349]
When I receive a notification on Android, the icon showing up is always blank. I am registering as follows,

Version: 1.3.0

```
settings =
      android:
        senderID: ###
      ios:
        alert: yes
        badge: yes
        sound: yes
```
The res folder in the android platform has all of the correct icons, so im a little stumped as to why they aren't showing up. The icon I get instead is a grey circle, with a white circle inside of it. I've even tried adding the 'icon' configuration attribute in there, and it doesn't work...

Really strange...any ideas?
